hw11 done
wuyntmm/study pull request #8
Opened 2023-01-10 11:32 UTC by wuyntmm

2023-01-12 22:25 UTC, klymenok requested changes

2023-01-12 22:25 UTC, klymenok commented on hw11.py
> +    print(f'You called function "{func.__name__}" on {time.ctime()}')
This log should be inside the `inner_deco_func` to work only when a decorated function is called but not when the decorator initialized

2023-01-12 22:25 UTC, klymenok commented on hw11.py
> +    def inner_deco_func():
Add here *args and **kwargs arguments and pass them to the `func` call to be able to decorate functions that take arguments

2023-01-12 22:25 UTC, klymenok commented on hw11.py
> +        func()
It is better to use `return` statement here since decorated functions can return some value

2023-01-15 17:41 UTC, wuyntmm commented
done

2023-01-16 22:51 UTC, klymenok approved these changes
Looks good!

2023-01-17 07:55 UTC, merged