Hw12
wuyntmm/study pull request #9
Opened 2023-01-15 17:32 UTC by wuyntmm

hw12 done

2023-01-16 14:44 UTC, acman requested changes
LGTM! Only small fixes should be provided.

2023-01-16 14:44 UTC, acman commented on hw12/hw12_1.py
> +    with open('json') as file:
if you expect json data in file - name it something like `phonebook.json` using json extention

2023-01-16 14:44 UTC, acman commented on hw12/hw12_1.py
> +                if len(users_input.split()) > 2:
you use `users_input.split()` a lot of times, better to set it to variable

2023-01-16 17:41 UTC, wuyntmm commented
Fixed

2023-01-18 11:45 UTC, acman approved these changes
nice job!

2023-01-18 13:04 UTC, merged